import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'id' | 'en';

export interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, defaultText?: string) => string;
}

export const translations: Record<Language, Record<string, string>> = {
  id: {
    // Navbar
    'nav.home': 'Beranda',
    'nav.catalog': 'Katalog',
    'nav.clients': 'Klien',
    'nav.reviews': 'Ulasan',
    'nav.gallery': 'Galeri',
    'nav.legality': 'Legalitas',
    'nav.contact': 'Kontak',
    'nav.admin': 'Admin',
    'nav.order_online': 'Order Online',
    'nav.whatsapp_chat': 'Chat MinSora',

    // Hero Section
    'hero.food_partner_badge': 'Food & Health Partner',
    'hero.halal_badge': 'Sertifikat Halal Resmi BPJPH RI',
    'hero.sanitation_badge': 'Laik Higiene Jasaboga',
    'hero.title_sub': 'PT. ASASORA BIO HEALTHORA',
    'hero.tagline': '"PRODUK TERSERTIFIKASI HALAL BPJPH"',
    'hero.description': 'Produk berkualitas yang di hasil kan dari pangan yang aman serta halal.',
    'hero.btn_order': 'Pesan Sekarang',
    'hero.btn_catalog': 'Lihat Katalog Menu',
    'hero.btn_consult': 'Chat WhatsApp MinSora',
    'hero.vp1_title': '100% Halal Resmi',
    'hero.vp1_desc': 'Bahan Baku Terjamin',
    'hero.vp2_title': 'Higienis & Sanitasi',
    'hero.vp2_desc': 'Standar Jasaboga',
    'hero.vp3_title': 'Cek Ongkir Otomatis',
    'hero.vp3_desc': '7 Opsi Kurir',
    'hero.card_halal_tag': 'TERSERTIFIKASI HALAL RESMI',
    'hero.card_trust1': '100% Bahan Baku & Dapur Halal',
    'hero.card_trust2': 'Standar Sanitasi & Uji Higiene',
    'hero.card_btn_verify': 'Verifikasi Dokumen Legalitas',

    // Catalog Section
    'catalog.tag': 'Pilihan Produk',
    'catalog.title': 'Pilihan Produk',
    'catalog.subtitle': 'Setiap hidangan diolah dari bahan segar pilihan, dijamin 100% Halal BPJPH dan diproses dengan standar higienis jasaboga.',
    'catalog.all': 'Semua Produk',
    'catalog.cat_all': 'Semua Produk',
    'catalog.cat_catering': 'catering & event',
    'catalog.cat_ready_to_eat': 'Produk Siap Santap',
    'catalog.cat_snack': 'Snak dan cemilan',
    'catalog.search_placeholder': 'Cari produk katering atau camilan...',
    'catalog.badge_halal': 'Halal BPJPH',
    'catalog.sold': 'Terjual',
    'catalog.like': 'Suka',
    'catalog.liked': 'Disukai',
    'catalog.price_label': 'Harga Menu',
    'catalog.btn_add_cart': '+ Keranjang',
    'catalog.btn_added': 'Ditambahkan!',
    'catalog.btn_order_now': 'Pesan Sekarang',
    'catalog.share_label': 'Bagikan',
    'catalog.btn_copied': 'Tersalin!',
    'catalog.btn_copy_link': 'Salin Link',
    'catalog.not_found': 'Produk tidak ditemukan',
    'catalog.not_found_sub': 'Coba cari dengan kata kunci lain atau pilih kategori "Semua Produk".',
    'catalog.reset_filter': 'Reset Filter',
    'catalog.read_more': 'Selengkapnya',
    'catalog.read_less': 'Tutup',

    // Order & Shipping Section
    'order.modal_title': 'Formulir Order Online & Keranjang',
    'order.modal_sub': 'Otomatisasi Kurir & Invoice Resmi',
    'order.close': 'Tutup',
    'order.tag': 'Formulir Pesanan Resmi',
    'order.title': 'Keranjang Belanja & Otomatisasi Kurir',
    'order.subtitle': 'Pilih menu katering, tentukan titik lokasi koordinat, pilih armada kurir (Gojek / Grab / Lalamove / Toko), lalu buat order untuk mendapatkan Invoice Resmi otomatis.',
    'order.step1': '1. Informasi Pelanggan',
    'order.name': 'Nama Lengkap',
    'order.name_placeholder': 'Contoh: Budi Santoso',
    'order.phone': 'Nomor WhatsApp / Telepon',
    'order.phone_placeholder': 'Contoh: 0812-3456-7890',
    'order.email': 'Email (Untuk Lampiran Invoice)',
    'order.email_placeholder': 'Contoh: budi.santoso@email.com (opsional)',
    'order.address': 'Alamat Kirim Lengkap',
    'order.address_placeholder': 'Jalan, Nomor Rumah, RT/RW, Kelurahan, Kecamatan, Kota, Kode Pos',

    'order.step2': '2. Daftar Produk Pilihan (Keranjang)',
    'order.add_more': 'Tambah Macam Produk Lain',
    'order.cart_empty': 'Keranjang Anda masih kosong.',
    'order.cart_empty_sub': 'Pilih menu katering di atas atau klik "Tambah Macam Produk Lain".',
    'order.quantity': 'Jumlah',
    'order.subtotal': 'Subtotal',
    'order.item_label': 'Produk Pilihan',

    'order.step3': '3. Sistem Otomatisasi Kurir & Cek Ongkir Geokoding',
    'order.geocoding_badge': 'Formula Geokoding Real-Time',
    'order.warehouse_origin': 'Gudang Dapur Asal (Statis)',
    'order.warehouse_tag': 'Dapur Pusat Asasora Tangerang',
    'order.search_address': 'Cari Alamat / Titik Lokasi Rumah (Geokoding Terintegrasi)',
    'order.search_provider': 'Peta OpenStreetMap',
    'order.search_placeholder': 'Ketik nama jalan / kelurahan / area (contoh: Cipondoh, BSD, Karawaci, Sudirman)...',
    'order.or_select_preset': 'Atau Pilih Preset Titik Cepat Jabodetabek:',
    'order.lat_label': 'Latitude Rumah',
    'order.lng_label': 'Longitude Rumah',
    'order.btn_gps': 'Gunakan GPS Lokasi Saya',
    'order.btn_calc_dist': 'Hitung Jarak Koordinat',
    'order.dist_result': 'Jarak Terhitung',
    'order.from_store': 'dari Gudang Asasora Tangerang',
    'order.choose_shipping': 'Pilih Metode & Tarif Kurir:',
    'order.filter_all': 'Semua Kurir (7 Opsi)',
    'order.filter_motor': '🛵 Motor (3)',
    'order.filter_mobil': '🚗 Mobil (3)',
    'order.filter_toko': '🏪 Toko',
    'order.courier_group_motor': 'A. KELOMPOK MOTOR / RODA DUA',
    'order.courier_group_car': 'B. KELOMPOK MOBIL / RODA EMPAT',
    'order.courier_group_store': 'C. KURIR TOKO (KHUSUS ASASORA)',
    'order.out_of_store_coverage': 'Di luar area Kurir Toko (Maks. 12 Km)',
    'order.out_of_instant_coverage': 'Jarak pengiriman melebihi batas kurir instan reguler (> 40 Km). Untuk pengiriman katering jarak jauh / luar kota, kami menyediakan layanan khusus dengan armada berpendingin & jadwal khusus.',
    'order.btn_wa_out_of_town': 'Hubungi Admin via WhatsApp untuk Pengiriman Luar Kota',

    'order.step4': '4. Rincian Total Pembayaran',
    'order.menu_count': 'Macam Menu',
    'order.total_products': 'Subtotal Produk',
    'order.portions': 'porsi',
    'order.shipping_fee': 'Ongkos Kirim',
    'order.choose_courier_first': 'Pilih Kurir Di Atas',
    'order.subtotal_accumulated': 'TOTAL SEMENTARA',
    'order.unique_code_note': '* Kode unik verifikasi otomatis (3 digit) akan ditambahkan saat invoice resmi diterbitkan.',
    'order.btn_create_invoice': 'Buat Order & Terbitkan Invoice Resmi',

    'order.step5': 'Langkah Terakhir: Pembayaran',
    'order.invoice_issued': 'Invoice Pesanan Telah Terbit',
    'order.invoice_sub': 'Data pesanan Anda telah dikonversi menjadi Invoice Resmi berformat siap cetak & unduh.',

    // Invoice View
    'invoice.tab_visual': 'Tampilan Lembar Invoice',
    'invoice.tab_text': 'Format Teks WhatsApp',
    'invoice.btn_copy_text': 'Salin Teks Invoice',
    'invoice.btn_copied': 'Tersalin!',
    'invoice.btn_download_pdf': 'Unduh PDF Resmi',
    'invoice.btn_print': 'Cetak Invoice',
    'invoice.title': 'FAKTUR / INVOICE RESMI',
    'invoice.subtitle': 'FOOD SERVICE & CATERING HALAL',
    'invoice.inv_number': 'Nomor Invoice:',
    'invoice.trx_date': 'Tanggal Transaksi:',
    'invoice.due_date': 'Batas Pembayaran:',
    'invoice.bill_to': 'TAGIHAN KEPADA (PELANGGAN):',
    'invoice.cust_name': 'Nama Pemesan:',
    'invoice.cust_phone': 'No. WhatsApp:',
    'invoice.cust_email': 'Email:',
    'invoice.cust_address': 'Alamat Pengiriman:',
    'invoice.shipping_method': 'Metode Pengiriman:',
    'invoice.table_no': 'No',
    'invoice.table_item': 'Nama Menu / Produk',
    'invoice.table_qty': 'Jumlah',
    'invoice.table_price': 'Harga Satuan',
    'invoice.table_total': 'Total',
    'invoice.subtotal_items': 'Subtotal Menu:',
    'invoice.shipping_cost': 'Biaya Pengiriman (Ongkir):',
    'invoice.unique_code': 'Kode Unik Verifikasi:',
    'invoice.total_bill': 'TOTAL TAGIHAN TRANSFER:',
    'invoice.payment_info': 'INSTRUKSI PEMBAYARAN TRANSFER BANK',
    'invoice.bank_name': 'Bank Central Asia (BCA)',
    'invoice.acc_number': 'Nomor Rekening:',
    'invoice.acc_holder': 'Atas Nama:',
    'invoice.btn_copy_acc': 'Salin No. Rekening',
    'invoice.payment_code': 'Kode Pembayaran:',
    'invoice.status_pending': 'Menunggu Pembayaran (Maks 24 Jam)',

    // Testimonials / Reviews
    'reviews.tag': 'Testimoni & Penilaian',
    'reviews.title': 'Review Pelanggan',
    'reviews.subtitle': 'Bagikan pengalaman Anda atau lihat ulasan otentik dari instansi, korporat, dan pelanggan setia kami.',
    'reviews.section_heading': 'Ulasan Terbaru Pelanggan',
    'reviews.verified': 'Terverifikasi',
    'reviews.form_title': 'Tulis Review Anda',
    'reviews.form_subtitle': 'Ulasan Anda akan langsung tampil setelah dikirim untuk membantu pelanggan lain.',
    'reviews.form_success': 'Terima kasih! Ulasan Anda telah berhasil diterbitkan.',
    'reviews.name_label': 'Nama Lengkap',
    'reviews.name_placeholder': 'Contoh: Budi Santoso',
    'reviews.company_label': 'Instansi / Perusahaan (Opsional)',
    'reviews.company_placeholder': 'Contoh: PT. Cipta Megah / Pribadi',
    'reviews.rating_label': 'Rating Kepuasan',
    'reviews.comment_label': 'Tulis Pengalaman & Ulasan Anda',
    'reviews.comment_placeholder': 'Ceritakan kepuasan Anda mengenai rasa, ketepatan waktu pengiriman, kebersihan kemasan...',
    'reviews.btn_submit': 'Kirim Review Sekarang',

    // Legality Section
    'legality.tag': 'Dokumen Perusahaan',
    'legality.title': 'Legalitas PT. ASASORA BIO HEALTHORA',
    'legality.subtitle': 'Dokumen legalitas resmi perusahaan yang terdaftar dan terverifikasi pada kementerian dan dinas terkait Republik Indonesia.',
    'legality.issuer': 'Penerbit:',
    'legality.validity': 'Masa Berlaku:',
    'legality.btn_view': 'Lihat Lembar Dokumen',
    'legality.verified': 'Sah & Legal',
    'legality.modal_title': 'Lembar Dokumen Legalitas',
    'legality.modal_close': 'Tutup',

    // Clients
    'clients.tag': 'Mitra & Rekanan',
    'clients.title': 'Our Client',
    'clients.subtitle': 'Berbagai instansi pemerintah, perusahaan korporat, fasilitas kesehatan, dan institusi pendidikan yang telah mempercayakan kebutuhan katering & penyediaan konsumsi higienis kepada PT. Asasora Bio Healthora.',
    'clients.verified': 'Mitra Terverifikasi',

    // Gallery
    'gallery.tag': 'Dokumentasi & Aktivitas',
    'gallery.title': 'Galeri Perusahaan',
    'gallery.subtitle': 'Potret kegiatan Asasora Catering, standar kebersihan dapur halal, penyiapan makanan olahan higienis, dan dokumentasi event korporat.',
    'gallery.tab_all': 'Semua Dokumentasi',
    'gallery.tab_kitchen': '🍳 Dapur & Sanitasi',
    'gallery.tab_event': '🍱 Event & Nasi Box',
    'gallery.tab_frozen': '🍲 Olahan & Frozen',
    'gallery.view_detail': 'Lihat Detail Foto',

    // Contact
    'contact.tag': 'Hubungi Kami',
    'contact.title': 'Siap Berkolaborasi dengan PT. ASASORA BIO HEALTHORA?',
    'contact.subtitle': 'Diskusikan kebutuhan katering korporat, nasi kotak/boks harian pabrik & kantor, paket prasmanan event, aneka makanan olahan/frozen siap saji, maupun aneka minuman segar bersama tim profesional Asasora.',
    'contact.address_title': 'Alamat Kantor',
    'contact.email_title': 'Email Resmi',
    'contact.wa_title': 'WhatsApp Customer Care (MinSora)',
    'contact.hours_title': 'Jam Operasional & Pengiriman',
    'contact.hours_desc': 'Senin - Minggu (06.00 - 21.00 WIB)',
    'contact.form_title': 'Kirim Pertanyaan / Penawaran',
    'contact.form_sub': 'Isi formulir singkat di bawah untuk terhubung langsung dengan MinSora Customer Care via WhatsApp.',
    'contact.name_label': 'Nama Anda / Nama Perusahaan',
    'contact.name_placeholder': 'Contoh: Ibu Rina / PT. Cipta Karya Gemilang',
    'contact.topic_label': 'Topik / Jenis Kebutuhan Katering',
    'contact.topic_opt1': 'Divisi Catering (Asasora Catering) - Nasi Kotak / Nasi Boks',
    'contact.topic_opt2': 'Paket Prasmanan & Catering Event Gathering',
    'contact.topic_opt3': 'Nasi Tumpeng Mini & Syukuran Nusantara',
    'contact.topic_opt4': 'Healthy Nutrition Diet & Meal Plan Sehat',
    'contact.topic_opt5': 'Snack Box Tradisional / Modern & Minuman',
    'contact.topic_opt6': 'Kerjasama Pengadaan Katering Harian Karyawan / Pabrik',
    'contact.message_label': 'Pesan / Detail Kebutuhan Acara',
    'contact.message_placeholder': 'Jelaskan tanggal acara, perkiraan jumlah porsi/pax, lokasi pengiriman, dan preferensi menu...',
    'contact.btn_submit': 'Hubungkan ke WhatsApp MinSora',

    // Floating Chat Mascot
    'float.chat_title': 'Chat MinSora',
    'float.chat_status': 'Online • Bantuan Cepat',

    // Footer
    'footer.quick_nav': 'Navigasi Cepat',
    'footer.nav_title': 'Navigasi Cepat',
    'footer.nav_home': 'Beranda (Home)',
    'footer.nav_catalog': 'Katalog Produk & Pemesanan',
    'footer.nav_order': 'Formulir Pesanan & Ongkir (Order Online)',
    'footer.nav_clients': 'Klien Kami (Our Client)',
    'footer.legal_docs': 'Legalitas & Dokumen',
    'footer.legality_title': 'Legalitas & Dokumen',
    'footer.doc_halal': 'Sertifikat Halal BPJPH',
    'footer.halal_cert': 'Sertifikat Halal BPJPH',
    'footer.doc_nib': 'NIB Berbasis Risiko OSS',
    'footer.nib_cert': 'NIB Berbasis Risiko OSS',
    'footer.doc_sanitation': 'Laik Higiene Sanitasi Jasaboga',
    'footer.hygiene_cert': 'Laik Higiene Sanitasi Jasaboga',
    'footer.doc_gallery': 'Galeri Dokumentasi Higiene',
    'footer.gallery_link': 'Galeri Dokumentasi Higiene',
    'footer.doc_reviews': 'Ulasan & Testimoni',
    'footer.reviews_link': 'Ulasan & Testimoni',
    'footer.payment_info': 'Informasi Pembayaran',
    'footer.bca_official': 'Rekening Bank BCA Resmi:',
    'footer.bank_account': 'Rekening Bank BCA Resmi:',
    'footer.bank_holder': 'A.N',
    'footer.open_hours': 'Buka:',
    'footer.all_rights': 'Hak Cipta Dilindungi.',
    'footer.rights_reserved': 'Hak Cipta Dilindungi.',
    'footer.back_to_top': 'Kembali ke Atas',

    // General & Misc
    'general.order_now': 'Order Online',
    'general.order': 'Order',
    'general.admin_panel': 'Panel Admin',
    'general.switch_lang': 'Ganti Bahasa',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.catalog': 'Catalog',
    'nav.clients': 'Clients',
    'nav.reviews': 'Reviews',
    'nav.gallery': 'Gallery',
    'nav.legality': 'Legality',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.order_online': 'Order Online',
    'nav.whatsapp_chat': 'Chat MinSora',

    // Hero Section
    'hero.food_partner_badge': 'Food & Health Partner',
    'hero.halal_badge': 'Official BPJPH Halal Certified',
    'hero.sanitation_badge': 'Food Sanitation Certified',
    'hero.title_sub': 'PT. ASASORA BIO HEALTHORA',
    'hero.tagline': '"BPJPH HALAL CERTIFIED PRODUCTS"',
    'hero.description': 'High-quality products produced from safe, hygienic, and authentic halal ingredients.',
    'hero.btn_order': 'Order Now',
    'hero.btn_catalog': 'View Menu Catalog',
    'hero.btn_consult': 'MinSora WhatsApp Chat',
    'hero.vp1_title': '100% Halal Certified',
    'hero.vp1_desc': 'Guaranteed BPJPH Ingredients',
    'hero.vp2_title': 'Hygienic & Sanitary',
    'hero.vp2_desc': 'Health Ministry Standards',
    'hero.vp3_title': 'Automated Shipping',
    'hero.vp3_desc': '7 Courier Fleet Options',
    'hero.card_halal_tag': 'OFFICIAL HALAL CERTIFIED',
    'hero.card_trust1': '100% Halal Ingredients & Kitchen',
    'hero.card_trust2': 'Sanitary Standards & Hygiene Tested',
    'hero.card_btn_verify': 'Verify Legality Documents',

    // Catalog Section
    'catalog.tag': 'Product Selection',
    'catalog.title': 'Product Selection',
    'catalog.subtitle': 'Every dish is crafted from freshly selected ingredients, 100% BPJPH Halal guaranteed, and processed according to catering hygiene standards.',
    'catalog.all': 'All Products',
    'catalog.cat_all': 'All Products',
    'catalog.cat_catering': 'Catering & Events',
    'catalog.cat_ready_to_eat': 'Ready-to-Eat Products',
    'catalog.cat_snack': 'Snacks & Refreshments',
    'catalog.search_placeholder': 'Search catering menus or snacks...',
    'catalog.badge_halal': 'Halal BPJPH',
    'catalog.sold': 'Sold',
    'catalog.like': 'Like',
    'catalog.liked': 'Liked',
    'catalog.price_label': 'Menu Price',
    'catalog.btn_add_cart': '+ Cart',
    'catalog.btn_added': 'Added!',
    'catalog.btn_order_now': 'Order Now',
    'catalog.share_label': 'Share',
    'catalog.btn_copied': 'Copied!',
    'catalog.btn_copy_link': 'Copy Link',
    'catalog.not_found': 'No products found',
    'catalog.not_found_sub': 'Try searching with other keywords or select the "All Products" category.',
    'catalog.reset_filter': 'Reset Filter',
    'catalog.read_more': 'Read More',
    'catalog.read_less': 'Show Less',

    // Order & Shipping Section
    'order.modal_title': 'Online Order Form & Cart',
    'order.modal_sub': 'Courier Automation & Official Invoice',
    'order.close': 'Close',
    'order.tag': 'Official Order Form',
    'order.title': 'Cart & Courier Automation',
    'order.subtitle': 'Select catering menus, set geocoded coordinate pinpoints, choose courier fleet (Gojek / Grab / Lalamove / Store Courier), and generate an instant Official Printable Invoice.',
    'order.step1': '1. Customer Information',
    'order.name': 'Full Name',
    'order.name_placeholder': 'e.g. John Doe',
    'order.phone': 'WhatsApp / Phone Number',
    'order.phone_placeholder': 'e.g. +62 812-3456-7890',
    'order.email': 'Email (For Electronic Invoice Attachment)',
    'order.email_placeholder': 'e.g. john.doe@email.com (optional)',
    'order.address': 'Complete Delivery Address',
    'order.address_placeholder': 'Street, House No., District, City, Postal Code',

    'order.step2': '2. Selected Menu Items (Cart)',
    'order.add_more': 'Add Another Menu Item',
    'order.cart_empty': 'Your cart is empty.',
    'order.cart_empty_sub': 'Select catering items above or click "Add Another Menu Item".',
    'order.quantity': 'Quantity',
    'order.subtotal': 'Subtotal',
    'order.item_label': 'Product Item',

    'order.step3': '3. Geocoded Courier Automation & Shipping Calculator',
    'order.geocoding_badge': 'Haversine Real-Time Engine',
    'order.warehouse_origin': 'Kitchen Origin Warehouse (Static)',
    'order.warehouse_tag': 'Asasora Central Hub Tangerang',
    'order.search_address': 'Search Delivery Address / Coordinate Pinpoint (Integrated Geocoding)',
    'order.search_provider': 'OpenStreetMap Map',
    'order.search_placeholder': 'Type street / area name (e.g. Cipondoh, BSD, Karawaci, Sudirman)...',
    'order.or_select_preset': 'Or Pick a Quick Jabodetabek Location Preset:',
    'order.lat_label': 'Delivery Latitude',
    'order.lng_label': 'Delivery Longitude',
    'order.btn_gps': 'Use My Device GPS',
    'order.btn_calc_dist': 'Calculate Coordinate Distance',
    'order.dist_result': 'Calculated Distance',
    'order.from_store': 'from Asasora Central Hub Tangerang',
    'order.choose_shipping': 'Choose Shipping Method:',
    'order.filter_all': 'All Couriers (7 Options)',
    'order.filter_motor': '🛵 Motorcycle (3)',
    'order.filter_mobil': '🚗 Car / Van (3)',
    'order.filter_toko': '🏪 Store',
    'order.courier_group_motor': 'A. MOTORCYCLE / 2-WHEEL FLEET',
    'order.courier_group_car': 'B. CAR / 4-WHEEL FLEET',
    'order.courier_group_store': 'C. ASASORA STORE DEDICATED COURIER',
    'order.out_of_store_coverage': 'Outside Store Courier Area (Max 12 Km)',
    'order.out_of_instant_coverage': 'Delivery distance exceeds regular instant courier limit (> 40 Km). For long-distance / out-of-town catering deliveries, we provide special temperature-controlled fleet services.',
    'order.btn_wa_out_of_town': 'Contact Admin on WhatsApp for Out-of-Town Delivery',

    'order.step4': '4. Total Payment Breakdown',
    'order.menu_count': 'Menu Items',
    'order.total_products': 'Product Subtotal',
    'order.portions': 'portions',
    'order.shipping_fee': 'Shipping Fee',
    'order.choose_courier_first': 'Select Courier Above',
    'order.subtotal_accumulated': 'SUBTOTAL',
    'order.unique_code_note': '* A unique 3-digit verification code will be generated upon invoice creation.',
    'order.btn_create_invoice': 'Create Order & Issue Official Invoice',

    'order.step5': 'Final Step: Payment',
    'order.invoice_issued': 'Order Invoice Issued',
    'order.invoice_sub': 'Your order has been converted into an Official Ready-to-Print Invoice format.',

    // Invoice View
    'invoice.tab_visual': 'Visual Invoice View',
    'invoice.tab_text': 'WhatsApp Plain Text Format',
    'invoice.btn_copy_text': 'Copy Invoice Text',
    'invoice.btn_copied': 'Copied!',
    'invoice.btn_download_pdf': 'Download Official PDF',
    'invoice.btn_print': 'Print Invoice',
    'invoice.title': 'OFFICIAL COMMERCIAL INVOICE',
    'invoice.subtitle': 'HALAL FOOD SERVICE & CATERING',
    'invoice.inv_number': 'Invoice No:',
    'invoice.trx_date': 'Transaction Date:',
    'invoice.due_date': 'Payment Due:',
    'invoice.bill_to': 'BILLED TO (CUSTOMER):',
    'invoice.cust_name': 'Customer Name:',
    'invoice.cust_phone': 'WhatsApp / Phone:',
    'invoice.cust_email': 'Email:',
    'invoice.cust_address': 'Delivery Address:',
    'invoice.shipping_method': 'Shipping Method:',
    'invoice.table_no': 'No',
    'invoice.table_item': 'Menu Item / Product Description',
    'invoice.table_qty': 'Qty',
    'invoice.table_price': 'Unit Price',
    'invoice.table_total': 'Total',
    'invoice.subtotal_items': 'Menu Items Subtotal:',
    'invoice.shipping_cost': 'Shipping Fee (Delivery):',
    'invoice.unique_code': 'Unique Verification Code:',
    'invoice.total_bill': 'TOTAL TRANSFER BILL:',
    'invoice.payment_info': 'BANK TRANSFER PAYMENT INSTRUCTIONS',
    'invoice.bank_name': 'Bank Central Asia (BCA)',
    'invoice.acc_number': 'Account Number:',
    'invoice.acc_holder': 'Account Holder:',
    'invoice.btn_copy_acc': 'Copy Account Number',
    'invoice.payment_code': 'Payment Code:',
    'invoice.status_pending': 'Awaiting Payment (Max 24 Hours)',

    // Testimonials / Reviews
    'reviews.tag': 'Testimonials & Ratings',
    'reviews.title': 'Customer Reviews',
    'reviews.subtitle': 'Share your experience or read authentic reviews from institutions, corporations, and our loyal customers.',
    'reviews.section_heading': 'Latest Customer Reviews',
    'reviews.verified': 'Verified',
    'reviews.form_title': 'Write Your Review',
    'reviews.form_subtitle': 'Your review will appear immediately after submission to help other customers.',
    'reviews.form_success': 'Thank you! Your review has been successfully published.',
    'reviews.name_label': 'Full Name',
    'reviews.name_placeholder': 'e.g. John Doe',
    'reviews.company_label': 'Institution / Company (Optional)',
    'reviews.company_placeholder': 'e.g. PT. Global Megah / Private',
    'reviews.rating_label': 'Satisfaction Rating',
    'reviews.comment_label': 'Write Your Experience & Feedback',
    'reviews.comment_placeholder': 'Tell us about your satisfaction regarding taste, delivery timeliness, packaging hygiene...',
    'reviews.btn_submit': 'Submit Review Now',

    // Legality Section
    'legality.tag': 'Corporate Documents',
    'legality.title': 'PT. ASASORA BIO HEALTHORA Legality',
    'legality.subtitle': 'Official corporate legality documents registered and verified with the relevant ministries and agencies of the Republic of Indonesia.',
    'legality.issuer': 'Issuer:',
    'legality.validity': 'Validity:',
    'legality.btn_view': 'View Document Sheet',
    'legality.verified': 'Valid & Official',
    'legality.modal_title': 'Corporate Legality Document',
    'legality.modal_close': 'Close',

    // Clients
    'clients.tag': 'Partners & Associates',
    'clients.title': 'Our Clients',
    'clients.subtitle': 'Various government agencies, corporate enterprises, healthcare facilities, and educational institutions that have trusted PT. Asasora Bio Healthora for their catering & hygienic food service needs.',
    'clients.verified': 'Verified Partner',

    // Gallery
    'gallery.tag': 'Documentation & Activities',
    'gallery.title': 'Company Gallery',
    'gallery.subtitle': 'Photos of Asasora Catering activities, halal kitchen hygiene standards, ready-to-eat food preparation, and corporate event catering documentation.',
    'gallery.tab_all': 'All Documentation',
    'gallery.tab_kitchen': '🍳 Kitchen & Sanitation',
    'gallery.tab_event': '🍱 Events & Meal Boxes',
    'gallery.tab_frozen': '🍲 Processed & Frozen',
    'gallery.view_detail': 'View Photo Details',

    // Contact
    'contact.tag': 'Contact Us',
    'contact.title': 'Ready to Collaborate with PT. ASASORA BIO HEALTHORA?',
    'contact.subtitle': 'Discuss your corporate catering, daily factory & office lunch boxes, buffet gathering packages, ready-to-eat/frozen foods, and refreshing beverages with the professional team at Asasora.',
    'contact.address_title': 'Office Address',
    'contact.address_label': 'Office Address',
    'contact.email_title': 'Official Email',
    'contact.email_label': 'Official Email',
    'contact.wa_title': 'WhatsApp Customer Care (MinSora)',
    'contact.wa_label': 'WhatsApp Customer Care (MinSora)',
    'contact.hours_title': 'Operational & Delivery Hours',
    'contact.hours_label': 'Operational & Delivery Hours',
    'contact.hours_desc': 'Monday - Sunday (06:00 - 21:00 WIB)',
    'contact.form_title': 'Send Inquiry / RFQ',
    'contact.form_sub': 'Fill out the quick form below to connect directly with MinSora Customer Care via WhatsApp.',
    'contact.form_subtitle': 'Fill out the quick form below to connect directly with MinSora Customer Care via WhatsApp.',
    'contact.form_name_label': 'Your Name / Company Name',
    'contact.name_label': 'Your Name / Company Name',
    'contact.name_placeholder': 'e.g. Mrs. Sarah / PT. Acme Global Solutions',
    'contact.form_name_placeholder': 'e.g. Mrs. Sarah / PT. Acme Global Solutions',
    'contact.form_topic_label': 'Catering / Product Requirement Division',
    'contact.topic_label': 'Topic / Catering Requirement',
    'contact.topic_opt1': 'Catering Division (Asasora Catering) - Meal Box / Lunch Box',
    'contact.topic_opt2': 'Buffet Packages & Gathering Event Catering',
    'contact.topic_opt3': 'Mini Tumpeng & Indonesian Ceremonial Feast',
    'contact.topic_opt4': 'Healthy Nutrition Diet & Wellness Meal Plan',
    'contact.topic_opt5': 'Traditional / Modern Snack Box & Beverages',
    'contact.topic_opt6': 'Daily Corporate & Factory Employee Meal Procurement',
    'contact.form_msg_label': 'Message / Requirement Details & RFQ',
    'contact.message_label': 'Message / Event Requirement Details',
    'contact.message_placeholder': 'Please specify event date, estimated portion/pax count, delivery location, and menu preferences...',
    'contact.form_msg_placeholder': 'Please specify event date, estimated portion/pax count, delivery location, and menu preferences...',
    'contact.btn_submit': 'Connect to MinSora WhatsApp',

    // Floating Chat Mascot
    'float.chat_title': 'Chat MinSora',
    'float.chat_status': 'Online • Quick Support',

    // Footer
    'footer.quick_nav': 'Quick Navigation',
    'footer.nav_title': 'Quick Navigation',
    'footer.nav_home': 'Home',
    'footer.nav_catalog': 'Product Catalog & Ordering',
    'footer.nav_order': 'Order Form & Shipping (Order Online)',
    'footer.nav_clients': 'Our Clients',
    'footer.legal_docs': 'Legality & Documents',
    'footer.legality_title': 'Legality & Documents',
    'footer.doc_halal': 'BPJPH Halal Certificate',
    'footer.halal_cert': 'BPJPH Halal Certificate',
    'footer.doc_nib': 'OSS Risk-Based Business ID (NIB)',
    'footer.nib_cert': 'OSS Risk-Based Business ID (NIB)',
    'footer.doc_sanitation': 'Food Service Sanitation & Hygiene Certificate',
    'footer.hygiene_cert': 'Food Service Sanitation & Hygiene Certificate',
    'footer.doc_gallery': 'Hygiene Documentation Gallery',
    'footer.gallery_link': 'Hygiene Documentation Gallery',
    'footer.doc_reviews': 'Reviews & Testimonials',
    'footer.reviews_link': 'Reviews & Testimonials',
    'footer.payment_info': 'Payment Information',
    'footer.bca_official': 'Official BCA Bank Account:',
    'footer.bank_account': 'Official BCA Bank Account:',
    'footer.bank_holder': 'A/N',
    'footer.open_hours': 'Open:',
    'footer.all_rights': 'All Rights Reserved.',
    'footer.rights_reserved': 'All Rights Reserved.',
    'footer.back_to_top': 'Back to Top',

    // General & Misc
    'general.order_now': 'Order Online',
    'general.order': 'Order',
    'general.admin_panel': 'Admin Panel',
    'general.switch_lang': 'Switch Language',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'id',
  setLang: () => {},
  t: (key: string, defaultText?: string) => defaultText || key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem('asasora_lang');
    return saved === 'en' ? 'en' : 'id';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('asasora_lang', newLang);
  };

  const t = (key: string, defaultText?: string): string => {
    return translations[lang]?.[key] || defaultText || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
